trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  TARGET_URL: 'https://google.com'

stages:
- stage: BuildAndScan
  jobs:
  - job: Build
    displayName: 'Build Application'

    steps:
    - task: SonarCloudPrepare@2
      inputs:
        SonarCloud: 'sonarqube-pwc'
        organization: sonamsoni2415
        scannerMode: 'CLI'
        configMode: 'manual'
        cliProjectKey: 'sonamsoni2415_DevOps-Example'
        extraProperties: |
          sonar.sources=src/main/java
          sonar.tests=src/test/java
          
    - task: Maven@4
      displayName: Build Application
      inputs:
        mavenPomFile: 'pom.xml'
        goals: 'clean package'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        jdkVersionOption: '1.11'
        sonarQubeRunAnalysis: true

   # - task: SonarCloudPublish@2
   #   displayName: 'Publish SonarQube Quality Gate'
    #  inputs:
     #   pollingTimeoutSec: '300'

# ==========================
# DAST Scan with ZAP
# ==========================
- stage: SecurityScan
  displayName: 'Run DAST Security Scan'
  dependsOn: BuildAndScan

  jobs:
  - job: ZAPScan
    displayName: 'OWASP ZAP Baseline Scan'

    steps:

    - script: |
        mkdir -p $(System.DefaultWorkingDirectory)/zap-reports
      displayName: 'Create Report Directory'

    - script: |
        docker run --user root \
        -v $(System.DefaultWorkingDirectory)/zap-reports:/zap/wrk:rw \
        -t zaproxy/zap-stable \
        zap-baseline.py \
        -t $(TARGET_URL) \
        -r zap_report.html \
        -x zap_report.xml
      displayName: 'Execute ZAP Baseline Scan'
      continueOnError: true

    - task: PublishBuildArtifacts@1
      displayName: 'Publish ZAP Reports'
      inputs:
        PathtoPublish: '$(System.DefaultWorkingDirectory)/zap-reports'
        ArtifactName: 'ZAP_Security_Reports'
        publishLocation: 'Container'
