trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  TARGET_URL: 'https://google.com'

# ==========================
# Stage 1 - Build
# ==========================
stages:

- stage: Build
  displayName: 'Build Application'

  jobs:
  - job: MavenBuild

    steps:
    - checkout: self

    - task: Maven@4
      displayName: 'Build Application'
      inputs:
        mavenPomFile: 'pom.xml'
        goals: 'clean package'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        jdkVersionOption: '1.11'

    - task: PublishPipelineArtifact@1
      displayName: 'Publish Build Artifact'
      inputs:
        targetPath: '$(System.DefaultWorkingDirectory)'
        artifact: 'source-code'

# ==========================
# Stage 2 - SonarCloud SAST
# ==========================

- stage: SonarScan
  displayName: 'SonarCloud Analysis'
  dependsOn: Build

  jobs:
  - job: Sonar

    steps:

    - checkout: self

    - task: SonarCloudPrepare@2
      inputs:
        SonarCloud: 'sonarqube-pwc'
        organization: 'sonamsoni2415'
        scannerMode: 'CLI'
        configMode: 'manual'
        cliProjectKey: 'sonamsoni2415_DevOps-Example'
        extraProperties: |
          sonar.sources=src/main/java
          sonar.tests=src/test/java

    - task: Maven@4
      displayName: 'Run Sonar Analysis'
      inputs:
        mavenPomFile: 'pom.xml'
        goals: 'verify'
        jdkVersionOption: '1.11'
        sonarQubeRunAnalysis: true

    - task: SonarCloudPublish@2
      displayName: 'Publish Quality Gate'
      inputs:
        pollingTimeoutSec: '300'

# ==========================
# Stage 3 - DAST
# ==========================

- stage: DAST
  displayName: 'OWASP ZAP Scan'
  dependsOn: SonarScan

  jobs:
  - job: ZAPScan

    steps:

    - script: |
        mkdir -p $(System.DefaultWorkingDirectory)/zap-reports
      displayName: 'Create Report Directory'

    - script: |
        docker run --user root \
        -v $(System.DefaultWorkingDirectory)/zap-reports:/zap/wrk:rw \
        -t zaproxy/zap-stable \
        zap-baseline.py \
        -t $(TARGET_URL) \
        -r zap_report.html \
        -x zap_report.xml
      displayName: 'Execute ZAP Baseline Scan'
      continueOnError: true

    - task: PublishBuildArtifacts@1
      displayName: 'Publish ZAP Reports'
      inputs:
        PathtoPublish: '$(System.DefaultWorkingDirectory)/zap-reports'
        ArtifactName: 'ZAP_Security_Reports'
        publishLocation: 'Container'
